txgh:
    github:
        repos:
            matthewjackowski/txgh-test-resources:
                api_username: <%= ENV['GITHUB_USERNAME']  %>
                api_token: <%= ENV['GITHUB_TOKEN'] %>
                push_source_to: txgh-test-1
                branch: master
    transifex:
        projects:
            txgh-test-1:
                tx_config: <%= ENV['TX_CONFIG_PATH'] %>
                api_username: <%= ENV['TX_USERNAME'] %>
                api_password: <%= ENV['TX_PASSWORD'] %>
                push_translations_to: matthewjackowski/txgh-test-resources
