txgh:
    github:
        repos:
            <your/full/repo/name>:
                api_username: <%= ENV['GITHUB_USERNAME'] %>
                api_token: <%= ENV['GITHUB_TOKEN'] %>
                push_source_to: <%= ENV['GITHUB_PUSH_SOURCE_TO'] %>
                branch: <%= ENV['GITHUB_BRANCH'] %>
    transifex:
        projects:
            <transifex project slug>:
                tx_config: <%= ENV['TX_CONFIG_PATH'] %>
                api_username: <%= ENV['TX_USERNAME'] %>
                api_password: <%= ENV['TX_PASSWORD'] %>
                push_translations_to: <%= ENV['TX_PUSH_TRANSLATIONS_TO'] %>